import { FC } from "react";
import Head from "next/head";
import { Header } from "../organisms/Header";
import { Footer } from "../organisms/Footer";
import { TopContent } from "../organisms/TopContent";

type Props = {
  title: string;
  children: ReactNode;
};

export const Template: FC<Props> = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopContent />
      <Footer />
    </div>
  );
};
